name: Bloquear PRs externos

on:
  pull_request:
    types:
      - opened

permissions:
  pull-requests: write
  issues: write

jobs:
  # JOB 1: VALIDAÇÃO DE AUTOR
  # Verifica se o usuário que abriu o PR é colaborador do repositório
  # Caso não seja:
  # - adiciona comentário automático
  # - fecha o Pull Request
  validate-pr-author:
    name: Validar autor do PR
    runs-on: ubuntu-latest

    steps:
      # A action github-script executa JavaScript usando a API do GitHub
      - name: Verificar se autor é colaborador
        uses: actions/github-script@v9
        with:
          script: |
            const author = context.payload.pull_request.user.login;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            try {
              await github.rest.repos.checkCollaborator({
                owner,
                repo,
                username: author
              });

            } catch {

              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: context.issue.number,
                body:
                  "PR fechado automaticamente. Apenas colaboradores podem abrir Pull Requests."
              });

              await github.rest.pulls.update({
                owner,
                repo,
                pull_number: context.issue.number,
                state: "closed"
              });
            }